### PR TITLE
handle explicit and implicit lambda name

### PR DESCRIPTION
**Pull request by Derek-X-Wang**
#31 

I didn't work with VS code plugin before. if you can share the debugging step. that will be very thankful.

So I can debug the code I change. anyway, this a simple fix but shall handle the explicit and implicit lambda names

### CODE REVIEW

**Comment by domagojk** [comment]
If you use `/aws/lambda/${lambdaName}` you won't be able to use tabs for multiple stages (because it will always be for the same stage). This is why I used a replace function to strip that part: https://github.com/domagojk/serverless-console/commit/d546ce8e5c062a3caa5672eaf087fb99f838e4c1

But that probably caused bugs for some users and I was planning to find out why.

Also, note that `serverless.yml` is not parsed in the extension - `serverless print` command is. I've noticed that some versions of serverless always prints resolved function names no matter if you define `name` or not and some older versions don't.

As for debugging, check this comment https://github.com/domagojk/serverless-console/issues/30#issuecomment-678119701

**Comment by Derek-X-Wang** [comment]
```
const lambdaName = yml.functions[fnName]?.name || `${yml.service.name}-${stage}-${fnName}`
```
is in  `service.stages.map((stage) => {`

so it will take different stages to compose the lambda name. or I missed something.

btw, 
```
➜  content-service git:(dev-stage) ✗ sls -version
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.12
```
this my sls version

**Comment by domagojk** [comment]
```
const lambdaName = yml.functions[fnName]?.name || `${yml.service.name}-${stage}-${fnName}`
```
this always resolves to
```
const lambdaName = yml.functions[fnName]?.name 
```

because (at least for newer versions of sls framework) name will always be there and then it won't work for users that have multiple stages defined

**Comment by Derek-X-Wang** [comment]
interesting, don't know that before.

can you give an example of the problematic `sls print` result. what's the name that will be in that case?

for example, case 1
```
functions:
  postCreateHandler:
    handler: src/post.create
    name: ${self:provider.stackName}-post-create
    tags:
      rest: mobz post api
    vpc:
      securityGroupIds:
        - !Ref LambdaSecurityGroup
      subnetIds:
        Fn::Split:
          - ","
          - Fn::ImportValue: ${self:provider.stage}-private-subnets
```
the `yml.functions[fnName]?.name` in this case shall be resolve correctly by `sls print`?

and case 2
```
functions:
  postCreateHandler:
    handler: src/post.create
    tags:
      rest: mobz post api
    vpc:
      securityGroupIds:
        - !Ref LambdaSecurityGroup
      subnetIds:
        Fn::Split:
          - ","
          - Fn::ImportValue: ${self:provider.stage}-private-subnets
```
the `yml.functions[fnName]?.name` will be resolve as `postCreateHandler` and then doesn't work in our stage?

Sry for bugging you, but this plugin is amazing. save my life from aws console :) really want to use it. and after version revert. doesn't work on my side. so I really would like to help :)

**Comment by Derek-X-Wang** [comment]
just saw your comment here
https://github.com/domagojk/serverless-console/issues/31#issuecomment-694105597

I think I get what you meant then

**Comment by domagojk** [comment]
@Derek-X-Wang If I don't think of a better solution, I will probably add an option where users can define if the stage should be resolved like this or not.

In the meantime, you can try using "cloudformation" service. You should be able to find the stack deployed from serverless and I think there should not be the same kind of bug

**Comment by Derek-X-Wang** [comment]
I update the logic a bit in the pull request. 

so in case of the name is missing in certain serverless version. we use the default name.

and in the case it always shows, we grab the yml.provider.stage. this is always the same. and replace that with the custom stage we need.

what you think

**Comment by domagojk** [comment]
I don't think this is good enough because the name of the stage can be included in the function name and it would be only a matter of time when new exceptions will arise because somebody has the "dev" or "prod" or whatever in their function name.

**Comment by Derek-X-Wang** [comment]
hmm. we can narrow it down a bit to replace `-stage-` assuming `${yml.service.name}-${stage}-${fnName}`

but this will not be stable either.

y, when the user defines the name, it can be anything. seem no way to parse that when supports multiple stages besides of asking user

**Comment by Derek-X-Wang** [comment]
thx for your explaination :)

**Comment by domagojk** [comment]
np, thanks for your effort :) I will solve this somehow, I just can't right now, but it's in my todo

**Pull request closed without merging**
